services:
  chaincode.peer0.medtechchain.nl:
    container_name: chaincode.peer0.medtechchain.nl
    image: medtechchain/chaincode
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CORE_PEER_LOCALMSPID: MedTechChainPeerMSP
      CORE_PEER_ADDRESS: peer0.medtechchain.nl:7052
      CORE_CHAINCODE_ID_NAME: medtechchain_1.0.0:98d1ff8118c098a001726dfbac54fae118f5e6899bbcc9df031a60c075454129
      CHAINCODE_SERVER_ADDRESS: 0.0.0.0:9999
      CORE_PEER_TLS_ENABLED: true
      CORE_PEER_TLS_ROOTCERT_FILE: /crypto/cert.pem
      CORE_TLS_CLIENT_KEY_PATH: /crypto/key.pem.b64
      CORE_TLS_CLIENT_KEY_FILE: /crypto/key.pem
      CORE_TLS_CLIENT_CERT_PATH: /crypto/cert.pem.b64
      CORE_TLS_CLIENT_CERT_FILE: /crypto/cert.pem
    ports:
      - "8061:9999"
    networks:
      - medtechchain
    volumes:
      - ./crypto/peer0.medtechchain.nl:/crypto

  chaincode.peer0.healpoint.nl:
    container_name: chaincode.peer0.healpoint.nl
    image: medtechchain/chaincode
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CORE_PEER_LOCALMSPID: HealPointPeerMSP
      CORE_PEER_ADDRESS: peer0.healpoint.nl:7052
      CORE_CHAINCODE_ID_NAME: medtechchain_1.0.0:98d1ff8118c098a001726dfbac54fae118f5e6899bbcc9df031a60c075454129
      CHAINCODE_SERVER_ADDRESS: 0.0.0.0:9999
      CORE_PEER_TLS_ENABLED: true
      CORE_PEER_TLS_ROOTCERT_FILE: /crypto/cert.pem
      CORE_TLS_CLIENT_KEY_PATH: /crypto/key.pem.b64
      CORE_TLS_CLIENT_KEY_FILE: /crypto/key.pem
      CORE_TLS_CLIENT_CERT_PATH: /crypto/cert.pem.b64
      CORE_TLS_CLIENT_CERT_FILE: /crypto/cert.pem
    ports:
      - "9061:9999"
    networks:
      - healpoint
    volumes:
      - ./crypto/peer0.healpoint.nl:/crypto

  chaincode.peer0.lifecare.nl:
    container_name: chaincode.peer0.lifecare.nl
    image: medtechchain/chaincode
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CORE_PEER_LOCALMSPID: LifeCarePeerMSP
      CORE_PEER_ADDRESS: peer0.lifecare.nl:7052
      CORE_CHAINCODE_ID_NAME: medtechchain_1.0.0:98d1ff8118c098a001726dfbac54fae118f5e6899bbcc9df031a60c075454129
      CHAINCODE_SERVER_ADDRESS: 0.0.0.0:9999
      CORE_PEER_TLS_ENABLED: true
      CORE_PEER_TLS_ROOTCERT_FILE: /crypto/cert.pem
      CORE_TLS_CLIENT_KEY_PATH: /crypto/key.pem.b64
      CORE_TLS_CLIENT_KEY_FILE: /crypto/key.pem
      CORE_TLS_CLIENT_CERT_PATH: /crypto/cert.pem.b64
      CORE_TLS_CLIENT_CERT_FILE: /crypto/cert.pem
    ports:
      - "10061:9999"
    networks:
      - lifecare
    volumes:
      - ./crypto/peer0.lifecare.nl:/crypto

networks:
  medtechchain:
    external: true
    name: medtechchain
  healpoint:
    external: true
    name: healpoint
  lifecare:
    external: true
    name: lifecare